# Generated by Django 4.0.1 on 2023-01-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('priority', models.CharField(choices=[('A', 'URGENTE'), ('B', 'MODERADO'), ('C', 'LEVE')], max_length=1)),
            ],
        ),
    ]
