# Generated by Django 4.0.1 on 2023-01-08 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completo',
            field=models.BooleanField(default=False),
        ),
    ]
